name: Update README

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1,13 * * *"
  push:
    branches:
      - "master"

jobs:
  markgen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # 使用 muesli/readme-scribe@master 操作，使用指定的模板生成 README 文件，并将其写入到项目的根目录中。
      - uses: muesli/readme-scribe@master
        # 使用者提供的令牌，可以让 Action 访问使用者在 GitHub 上的私有数据。
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"

      - uses: stefanzweifel/git-auto-commit-action@v7
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        with:
          commit_message: Update generated README
          branch: master
          commit_user_name: reoden 
          commit_user_email: staraino_o@163.com
          commit_author: reoden <staraino_o@163.com>
