name: Update README

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1,13 * * *"
  push:
    branches:
      - "main"
permissions:
  contents: write

jobs:
  markgen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - run: npm install

      - run: node generate-readme.js
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          USERNAME: reoden

      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Update generated README
          branch: main
          commit_user_name: Reoden
          commit_user_email: reodenx@gmail.com
          commit_author: Reoden <reodenx@gmail.com>
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
